version: '3.8'

services:
  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: kafka
    environment:
      # KRaft / controller settings (single-node broker + controller)
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_NODE_ID: "1"
      CLUSTER_ID: "m0zq4GveSmiE3L5hUogkiA"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,OUTSIDE://0.0.0.0:9094"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,OUTSIDE://localhost:29092"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_NUM_PARTITIONS: "3"
      KAFKA_LOG_DIRS: "/var/lib/kafka/data"
      # keep inter-broker listener mapped to PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,OUTSIDE:PLAINTEXT"
      # Important for single-node KRaft -- broker will format metadata if needed
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "9092:9092"
      - "29092:9094"  # Expose the external listener on port 29092
      - "9093:9093"   # Controller listener (mapped for completeness)
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    restart: unless-stopped
    networks:
      - confluent-net

networks:
  confluent-net:
    driver: bridge
